WARNING:tensorflow:From /home/grupo01/tensorflow/models/research/deeplab/core/conv2d_ws.py:40: The name tf.layers.Layer is deprecated. Please use tf.compat.v1.layers.Layer instead.

WARNING:tensorflow:From eval.py:227: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From eval.py:91: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0414 16:37:51.724200 140376495122176 module_wrapper.py:139] From eval.py:91: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From eval.py:91: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

W0414 16:37:51.724380 140376495122176 module_wrapper.py:139] From eval.py:91: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

WARNING:tensorflow:From eval.py:108: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

W0414 16:37:51.724594 140376495122176 module_wrapper.py:139] From eval.py:108: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:From eval.py:109: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

W0414 16:37:51.724846 140376495122176 module_wrapper.py:139] From eval.py:109: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

INFO:tensorflow:Evaluating on val_fine set
I0414 16:37:51.724936 140376495122176 eval.py:109] Evaluating on val_fine set
WARNING:tensorflow:From /home/grupo01/tensorflow/models/research/deeplab/datasets/data_generator.py:350: The name tf.gfile.Glob is deprecated. Please use tf.io.gfile.glob instead.

W0414 16:37:51.725837 140376495122176 module_wrapper.py:139] From /home/grupo01/tensorflow/models/research/deeplab/datasets/data_generator.py:350: The name tf.gfile.Glob is deprecated. Please use tf.io.gfile.glob instead.

WARNING:tensorflow:From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

W0414 16:37:51.943662 140376495122176 module_wrapper.py:139] From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

WARNING:tensorflow:From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.parse_single_example is deprecated. Please use tf.io.parse_single_example instead.

W0414 16:37:51.945336 140376495122176 module_wrapper.py:139] From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.parse_single_example is deprecated. Please use tf.io.parse_single_example instead.

2020-04-14 16:37:52.706599: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-04-14 16:37:52.812942: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:07:00.0
2020-04-14 16:37:52.813277: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-04-14 16:37:52.815977: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-04-14 16:37:52.817967: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-04-14 16:37:52.818285: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-04-14 16:37:52.820215: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-04-14 16:37:52.821629: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-04-14 16:37:52.827586: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-14 16:37:52.833991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
WARNING:tensorflow:From /home/grupo01/tensorflow/models/research/deeplab/datasets/data_generator.py:339: DatasetV1.make_one_shot_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_one_shot_iterator(dataset)`.
W0414 16:37:54.940582 140376495122176 deprecation.py:323] From /home/grupo01/tensorflow/models/research/deeplab/datasets/data_generator.py:339: DatasetV1.make_one_shot_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_one_shot_iterator(dataset)`.
INFO:tensorflow:Performing single-scale test.
I0414 16:37:54.959311 140376495122176 eval.py:127] Performing single-scale test.
WARNING:tensorflow:From /home/grupo01/tensorflow/models/research/deeplab/model.py:320: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

W0414 16:37:54.959659 140376495122176 module_wrapper.py:139] From /home/grupo01/tensorflow/models/research/deeplab/model.py:320: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

WARNING:tensorflow:From /home/grupo01/tensorflow/models/research/deeplab/core/feature_extractor.py:490: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0414 16:37:54.960054 140376495122176 deprecation.py:323] From /home/grupo01/tensorflow/models/research/deeplab/core/feature_extractor.py:490: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
WARNING:tensorflow:From /home/grupo01/tensorflow/models/research/deeplab/core/xception.py:469: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0414 16:37:54.962162 140376495122176 module_wrapper.py:139] From /home/grupo01/tensorflow/models/research/deeplab/core/xception.py:469: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
W0414 16:37:54.964537 140376495122176 deprecation.py:323] From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/grupo01/tensorflow/models/research/deeplab/core/utils.py:41: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.

W0414 16:37:59.386903 140376495122176 module_wrapper.py:139] From /home/grupo01/tensorflow/models/research/deeplab/core/utils.py:41: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.

WARNING:tensorflow:From eval.py:150: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0414 16:37:59.545325 140376495122176 deprecation.py:323] From eval.py:150: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From eval.py:161: The name tf.metrics.mean_iou is deprecated. Please use tf.compat.v1.metrics.mean_iou instead.

W0414 16:37:59.546240 140376495122176 module_wrapper.py:139] From eval.py:161: The name tf.metrics.mean_iou is deprecated. Please use tf.compat.v1.metrics.mean_iou instead.

WARNING:tensorflow:From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/metrics_impl.py:1178: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
W0414 16:37:59.625975 140376495122176 deprecation.py:323] From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/metrics_impl.py:1178: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
WARNING:tensorflow:From eval.py:171: The name tf.metrics.true_positives is deprecated. Please use tf.compat.v1.metrics.true_positives instead.

W0414 16:37:59.636407 140376495122176 module_wrapper.py:139] From eval.py:171: The name tf.metrics.true_positives is deprecated. Please use tf.compat.v1.metrics.true_positives instead.

WARNING:tensorflow:From eval.py:174: The name tf.metrics.false_positives is deprecated. Please use tf.compat.v1.metrics.false_positives instead.

W0414 16:37:59.654417 140376495122176 module_wrapper.py:139] From eval.py:174: The name tf.metrics.false_positives is deprecated. Please use tf.compat.v1.metrics.false_positives instead.

WARNING:tensorflow:From eval.py:177: The name tf.metrics.false_negatives is deprecated. Please use tf.compat.v1.metrics.false_negatives instead.

W0414 16:37:59.672217 140376495122176 module_wrapper.py:139] From eval.py:177: The name tf.metrics.false_negatives is deprecated. Please use tf.compat.v1.metrics.false_negatives instead.

WARNING:tensorflow:From eval.py:191: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

W0414 16:38:00.865505 140376495122176 module_wrapper.py:139] From eval.py:191: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From eval.py:192: Print (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2018-08-20.
Instructions for updating:
Use tf.print instead of tf.Print. Note that tf.print returns a no-output operator that directly prints the output. Outside of defuns or eager mode, this operator will not be executed unless it is directly specified in session.run or used as a control dependency for other operators. This is only a concern in graph mode. Below is an example of how to ensure tf.print executes in graph mode:

W0414 16:38:00.866816 140376495122176 deprecation.py:323] From eval.py:192: Print (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2018-08-20.
Instructions for updating:
Use tf.print instead of tf.Print. Note that tf.print returns a no-output operator that directly prints the output. Outside of defuns or eager mode, this operator will not be executed unless it is directly specified in session.run or used as a control dependency for other operators. This is only a concern in graph mode. Below is an example of how to ensure tf.print executes in graph mode:

WARNING:tensorflow:From eval.py:195: The name tf.summary.merge is deprecated. Please use tf.compat.v1.summary.merge instead.

W0414 16:38:00.899938 140376495122176 module_wrapper.py:139] From eval.py:195: The name tf.summary.merge is deprecated. Please use tf.compat.v1.summary.merge instead.

WARNING:tensorflow:From eval.py:208: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0414 16:38:00.901251 140376495122176 module_wrapper.py:139] From eval.py:208: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From eval.py:209: print_model_analysis (from tensorflow.contrib.tfprof.model_analyzer) is deprecated and will be removed after 2018-01-01.
Instructions for updating:
Use `tf.profiler.profile(graph, run_meta, op_log, cmd, options)`. Build `options` with `tf.profiler.ProfileOptionBuilder`. See README.md for details
W0414 16:38:00.901380 140376495122176 deprecation.py:323] From eval.py:209: print_model_analysis (from tensorflow.contrib.tfprof.model_analyzer) is deprecated and will be removed after 2018-01-01.
Instructions for updating:
Use `tf.profiler.profile(graph, run_meta, op_log, cmd, options)`. Build `options` with `tf.profiler.ProfileOptionBuilder`. See README.md for details
WARNING:tensorflow:From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/profiler/internal/flops_registry.py:142: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
W0414 16:38:00.902741 140376495122176 deprecation.py:323] From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/profiler/internal/flops_registry.py:142: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
61 ops no flops stats due to incomplete shapes.
61 ops no flops stats due to incomplete shapes.
INFO:tensorflow:Waiting for new checkpoint at ./datasets/cityscapes/exp/train_on_train_set/train/exp3
I0414 16:38:02.875864 140376495122176 evaluation.py:189] Waiting for new checkpoint at ./datasets/cityscapes/exp/train_on_train_set/train/exp3
INFO:tensorflow:Found new checkpoint at ./datasets/cityscapes/exp/train_on_train_set/train/exp3/model.ckpt-13468
I0414 16:38:02.878389 140376495122176 evaluation.py:198] Found new checkpoint at ./datasets/cityscapes/exp/train_on_train_set/train/exp3/model.ckpt-13468
INFO:tensorflow:Graph was finalized.
I0414 16:38:04.504878 140376495122176 monitored_session.py:240] Graph was finalized.
2020-04-14 16:38:04.505883: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-14 16:38:04.523784: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2099865000 Hz
2020-04-14 16:38:04.525124: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55b421218ef0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-14 16:38:04.525171: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-04-14 16:38:04.820876: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55b421adb370 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-04-14 16:38:04.820927: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): TITAN Xp, Compute Capability 6.1
2020-04-14 16:38:04.824053: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:07:00.0
2020-04-14 16:38:04.824174: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-04-14 16:38:04.824211: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-04-14 16:38:04.824243: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-04-14 16:38:04.824289: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-04-14 16:38:04.824320: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-04-14 16:38:04.824350: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-04-14 16:38:04.824381: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-14 16:38:04.833205: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-04-14 16:38:04.833432: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-04-14 16:38:04.837775: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-14 16:38:04.837797: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-04-14 16:38:04.837806: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-04-14 16:38:04.849246: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11438 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:07:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from ./datasets/cityscapes/exp/train_on_train_set/train/exp3/model.ckpt-13468
I0414 16:38:04.852164 140376495122176 saver.py:1284] Restoring parameters from ./datasets/cityscapes/exp/train_on_train_set/train/exp3/model.ckpt-13468
INFO:tensorflow:Running local_init_op.
I0414 16:38:50.707156 140376495122176 session_manager.py:500] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0414 16:38:51.197093 140376495122176 session_manager.py:502] Done running local_init_op.
INFO:tensorflow:Starting evaluation at 2020-04-14-14:39:15
I0414 16:39:15.012931 140376495122176 evaluation.py:450] Starting evaluation at 2020-04-14-14:39:15
2020-04-14 16:39:38.178241: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-14 16:39:44.769952: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-04-14 16:39:56.986224: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at spacetobatch_op.cc:219 : Invalid argument: padded_shape[0]=69 is not divisible by block_shape[0]=2
Traceback (most recent call last):
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: padded_shape[0]=69 is not divisible by block_shape[0]=2
	 [[{{node xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND}}]]
	 [[ConstantFoldingCtrl/mean_iou/confusion_matrix/assert_non_negative_1/assert_less_equal/Assert/AssertGuard/Switch_0/_4534]]
  (1) Invalid argument: padded_shape[0]=69 is not divisible by block_shape[0]=2
	 [[{{node xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval.py", line 227, in <module>
    tf.app.run()
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "eval.py", line 220, in main
    eval_interval_secs=FLAGS.eval_interval_secs)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/contrib/training/python/training/evaluation.py", line 453, in evaluate_repeatedly
    session.run(eval_ops, feed_dict)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1259, in run
    run_metadata=run_metadata)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1418, in run
    run_metadata=run_metadata)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1176, in run
    return self._sess.run(*args, **kwargs)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: padded_shape[0]=69 is not divisible by block_shape[0]=2
	 [[node xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND (defined at /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[ConstantFoldingCtrl/mean_iou/confusion_matrix/assert_non_negative_1/assert_less_equal/Assert/AssertGuard/Switch_0/_4534]]
  (1) Invalid argument: padded_shape[0]=69 is not divisible by block_shape[0]=2
	 [[node xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND (defined at /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND':
  File "eval.py", line 227, in <module>
    tf.app.run()
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "eval.py", line 129, in main
    image_pyramid=FLAGS.image_pyramid)
  File "/home/grupo01/tensorflow/models/research/deeplab/model.py", line 188, in predict_labels
    fine_tune_batch_norm=False)
  File "/home/grupo01/tensorflow/models/research/deeplab/model.py", line 323, in multi_scale_logits
    nas_training_hyper_parameters=nas_training_hyper_parameters)
  File "/home/grupo01/tensorflow/models/research/deeplab/model.py", line 577, in _get_logits
    nas_training_hyper_parameters=nas_training_hyper_parameters)
  File "/home/grupo01/tensorflow/models/research/deeplab/model.py", line 404, in extract_features
    use_bounded_activation=model_options.use_bounded_activation)
  File "/home/grupo01/tensorflow/models/research/deeplab/core/feature_extractor.py", line 643, in extract_features
    scope=name_scope[model_variant])
  File "/home/grupo01/tensorflow/models/research/deeplab/core/feature_extractor.py", line 710, in network_fn
    *args, **kwargs)
  File "/home/grupo01/tensorflow/models/research/deeplab/core/xception.py", line 744, in xception_65
    sync_batch_norm_method=sync_batch_norm_method)
  File "/home/grupo01/tensorflow/models/research/deeplab/core/xception.py", line 716, in xception_65_factory
    sync_batch_norm_method=sync_batch_norm_method)
  File "/home/grupo01/tensorflow/models/research/deeplab/core/xception.py", line 491, in xception
    net = stack_blocks_dense(net, blocks, output_stride)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/grupo01/tensorflow/models/research/deeplab/core/xception.py", line 402, in stack_blocks_dense
    net = block.unit_fn(net, rate=rate, **dict(unit, stride=1))
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/grupo01/tensorflow/models/research/deeplab/core/xception.py", line 308, in xception_module
    scope='separable_conv' + str(i+1))
  File "/home/grupo01/tensorflow/models/research/deeplab/core/xception.py", line 299, in _separable_conv
    scope=scope)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/grupo01/tensorflow/models/research/deeplab/core/xception.py", line 194, in separable_conv2d_same
    outputs = _split_separable_conv2d(padding='SAME')
  File "/home/grupo01/tensorflow/models/research/deeplab/core/xception.py", line 184, in _split_separable_conv2d
    **kwargs)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py", line 2827, in separable_convolution2d
    data_format=data_format)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_impl.py", line 819, in depthwise_conv2d
    op=op)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_ops.py", line 483, in with_space_to_batch
    return new_op(input, None)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_ops.py", line 639, in __call__
    return self.call(inp, filter)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_ops.py", line 622, in _with_space_to_batch_call
    input=inp, block_shape=dilation_rate, paddings=paddings)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 9652, in space_to_batch_nd
    paddings=paddings, name=name)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

